apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: quay.io/rbrhssa/ds-demo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: petclinic
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic
spec:
  to:
    kind: Service
    name: petclinic
  port:
    targetPort: 8080
  tls:
    termination: edge
