# ---- Stage 1: Build the application ----
FROM registry.access.redhat.com/ubi8/openjdk-17:latest AS builder

USER 0
WORKDIR /workspace
RUN chmod 777 /workspace

ENV HOME=/workspace
ENV MAVEN_CONFIG=/workspace/.m2

COPY pom.xml .
COPY pom.override.xml .
RUN microdnf install -y maven

COPY src ./src

RUN mvn -Dmaven.repo.local=/workspace/.m2/repository \
        -Dmaven.wagon.http.ssl.insecure=true \
        -Dmaven.wagon.http.ssl.allowall=true \
        -Dmaven.wagon.http.allowInsecure=true \
        -Dcheckstyle.skip=true \
        -Dnohttp.checkstyle.skip=true \
        -f pom.xml -f pom.override.xml \
        package -DskipTests -B

# ---- Stage 2: Create the runtime image ----
FROM registry.access.redhat.com/ubi8/openjdk-17-runtime:latest

WORKDIR /opt/app
COPY --from=builder /workspace/target/*.jar app.jar

EXPOSE 8080

USER 185

ENV JAVA_OPTS="-XX:MaxRAMPercentage=75.0"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
